services:
  - type: web
    name: groww-reviews-analyzer
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: GROQ_API_KEY
        sync: false
      - key: GROQ_API_KEY_FALLBACK
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: SMTP_HOST
        value: smtp.gmail.com
      - key: SMTP_PORT
        value: 587
      - key: SMTP_USER
        sync: false
      - key: SMTP_PASSWORD
        sync: false
      - key: API_TOKEN
        sync: false
